CREATE TABLE IF NOT EXISTS TACO_ORDER (
    ID IDENTITY PRIMARY KEY,
    DELIVERY_NAME VARCHAR(50) NOT NULL,
    DELIVERY_STREET VARCHAR(50) NOT NULL,
    DELIVERY_CITY VARCHAR(50) NOT NULL,
    DELIVERY_STATE VARCHAR(50) NOT NULL,
    DELIVERY_ZIP VARCHAR(10) NOT NULL,
    CC_NUMBER VARCHAR(16) NOT NULL,
    CC_EXPIRATION VARCHAR(5) NOT NULL,
    CC_CVV VARCHAR(3) NOT NULL,
    PLACED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TACO (
    ID IDENTITY PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    TACO_ORDER BIGINT NOT NULL,
    TACO_ORDER_KEY BIGINT NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS INGREDIENT_REF (
    INGREDIENT VARCHAR(4) NOT NULL,
    TACO BIGINT NOT NULL,
    TACO_KEY BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS INGREDIENT (
    ID VARCHAR(4) NOT NULL PRIMARY KEY,
    NAME VARCHAR(25) NOT NULL,
    TYPE VARCHAR(10) NOT NULL,
    VERSION INTEGER
);